#!/bin/bash
set -ex
usage() {
  echo "Usage: $0 [-b <bucket-name>] [-d <days>] [-e <exclude-folder>]... [-h]"
  echo "  -b <bucket-name>      Specify the S3 bucket path, including s3:// (default: use \$S3_BUCKET environment variable)"
  echo "  -d <days>             Specify the number of days for the threshold (default: 30)"
  echo "  -e <exclude-folder>   Specify folders to exclude (multiple can be provided)"
  echo "  -h                    Display this help message"
  exit 1
}

# Default values
bucket_name="$S3_BUCKET"
threshold_days=30
excluded_folders=()

while getopts ":b:d:e:h" opt; do
  case "$opt" in
    b)
      bucket_name="$OPTARG"
      ;;
    d)
      threshold_days="$OPTARG"
      ;;
    e)
      excluded_folders+=("$OPTARG")
      ;;
    h)
      usage
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

# Calculate the timestamp for the threshold
threshold_timestamp=$(date -d "$threshold_days days ago" +%s)
detected_file_list="/tmp/file_list_${threshold_timestamp}.txt"

# List all objects in the S3 bucket and filter those older than the threshold
aws s3 ls "${bucket_name}" --recursive --human-readable --summarize | \
grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}' | \
while read -r line; do
    timestamp=$(echo "$line" | awk '{print $1, $2}')
    file=$(echo "$line" | awk '{$1=$2=""; print $0}')
    file_timestamp=$(date -d "$timestamp" +%s)
    
    # Check if the file is in an excluded folder
    is_excluded=false
    for folder in "${excluded_folders[@]}"; do
        if [[ "$file" == *"$folder"* ]]; then
            is_excluded=true
            break
        fi
    done
    
    if [ "$file_timestamp" -lt "$threshold_timestamp" ] && [ "$is_excluded" = false ]; then
        echo "File: $file, Timestamp: $timestamp"
        echo "s3://${bucket_name}${file}" >> $detected_file_list
    fi
done

# Prompt to delete the file
read -r -p "Do you want to delete detected files? (yes/no): " delete_choice

if [[ "$delete_choice" == "yes" ]]; then
    while IFS= read -r line; do
        aws s3 rm "$line"
    done < "$detected_file_list"

    echo "File deletion complete"
else
    echo "No files were deleted."
fi
