#!/bin/bash

# Simple script to move files matching specified string into folder
# Useful when you have several files in the same folder and want to place them in individual folders by group 
# Script reads the matching string from a user provided list
# Set flags, recieve arguments
while getopts f:l: flag
do
	case "${flag}" in
		f) folder=${OPTARG};;
		p) list=${OPTARG};;
	esac
done

# Create dir if missing
mkdir -p $folder

# Loop through list and move matching files to folder
for i in $list; do
	mv "$i*" $folder
done

