#!/bin/bash
# This script drops all your koha databases. Be very careful!

# Prompt the user for the name of your koha instance(s). Input something simple and easily distinguishable from other instances.
read -p "Enter the name of each  Koha instance you want activate separated by a space:	" -a instance

# Prompt for source server
read -p "Enter the IP of your source server:  " sourceip

# Enable and start  Koha instances
for instancename in "${instance[@]}"; do


done

