#!/bin/bash

# Script to fix Koha DBMS autoincrement issue
# https://wiki.koha-community.org/wiki/DBMS_auto_increment_fix
# Actual script is courtesy of KohaAloha
# https://github.com/KohaAloha/koha-mysql-init
set -x
set -e

sudo  cp -a ./koha-mysql-init/koha-mysql-init.sh /etc/koha/
sudo  cp -a ./koha-mysql-init/koha-mysql-init.sql /etc/koha/
sudo  cp -a ./koha-mysql-init/koha-mysql-init.service  /etc/systemd/system/

# copy files
sudo systemctl enable  koha-mysql-init
sudo systemctl daemon-reload
sudo systemctl list-unit-files | grep koha


# execute init script, via mysql
sudo systemctl restart mysql

# confirm unit was run ok
sudo tail -f /var/log/syslog  | grep -i koha
