#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 instance_name user_id [user_id...]"
    exit 1
fi

instance="$1"
shift

while [ $# -gt 0 ]; do
    user_id="$1"
    patron_id=$(sudo koha-list --enabled --column="borrowernumber" --column="userid" | grep -E "^$user_id\s+" | awk '{ print $1 }')

    if [ -z "$patron_id" ]; then
        echo "Error: user ID not found: $user_id"
        continue
    fi

    password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1)

    if sudo koha-reset-password $instance $patron_id $password; then
        echo "Password for user $user_id set to: $password"
    else
        echo "Error: failed to set password for user $user_id"
    fi

    shift
done
