#!/bin/bash
# This script checks if the OPAC and Staff page URLs from your Apache config files are reachable

filename=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 5)

for i in $(koha-list); do
sudo sed -n /ServerName/p /etc/apache2/sites-enabled/$i.conf | sed 's/ServerName//g' | sed 's/#//g' | awk '{$1=$1};1' >> /tmp/$filename.txt
done;
while read url
do
        echo "Checking if $url is alive."
        curl -LIs https://$url | head -n 1
        echo  " "
done < <(tr ' ' '\n' < /tmp/$filename.txt)

# Delete temp file
rm /tmp/$filename.txt
