#!/bin/bash
set -e

# include helper functions
if [ -f "/usr/share/koha/bin/koha-functions.sh" ]; then
    . "/usr/share/koha/bin/koha-functions.sh"
else
    echo "Error: /usr/share/koha/bin/koha-functions.sh not present." 1>&2
    exit 1
fi

usage()
{
    local scriptname=$0
    cat <<EOF
Resets the password for the specified user on the Koha instance.

Usage: $scriptname instancename --userid <userid> [--password <password>] [--patron_id <patron_id>] [--cardnumber <cardnumber>]

Note: The generated password will be printed.
EOF
}

set_password()
{
    local instancename=$1
    local userid=$2
    local password=$3
    local patron_id=$4
    local cardnumber=$5

    if sudo -u "$instancename-koha" -H \
        env PERL5LIB="/usr/share/koha/lib" \
        KOHA_CONF="/etc/koha/sites/$instancename/koha-conf.xml" \
        /usr/share/koha/bin/admin/set_password.pl --userid "$userid" --password "$password" --patron_id "$patron_id" --cardnumber "$cardnumber"; then

        return 0
    else
        return 1
    fi
}

if [ $# -lt 2 ]; then
    usage
    die "Wrong parameters"
fi

instance="$1"
shift

userid=""
password=""
patron_id=""
cardnumber=""

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --userid)
    userid="$2"
    shift
    shift
    ;;
    --password)
    password="$2"
    shift
    shift
    ;;
    --patron_id)
    patron_id="$2"
    shift
    shift
    ;;
    --cardnumber)
    cardnumber="$2"
    shift
    shift
    ;;
    *)
    usage
    die "Unknown parameter: $1"
    ;;
esac
done

if [ -z "$userid" ]; then
    usage
    die "--userid is mandatory"
fi

set_password "$instance" "$userid" "$password" "$patron_id" "$cardnumber"

exit 0
