#!/bin/bash
set -euo pipefail

# This script updates the URL of your Koha database server.

function usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

This script updates the URL of your Koha database server.

OPTIONS:
  -i, --instance NAME1 NAME2...  Names of Koha instances to update.
  -u, --username USERNAME       Username of the database root user.
  -p, --password PASSWORD       Password of the database root user.
  -h, --hostname HOSTNAME       Hostname or URL of the new database server.
  -h, --help                    Display this help message.
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -i|--instance)
    instance=($2)
    shift
    shift
    ;;
    -u|--username)
    new_db_root="$2"
    shift
    shift
    ;;
    -p|--password)
    new_db_pass="$2"
    shift
    shift
    ;;
    -h|--hostname)
    hostname="$2"
    shift
    shift
    ;;
    --help)
    usage
    exit 0
    ;;
    *)
    echo "Unknown option: $1"
    usage
    exit 1
    ;;
esac
done

# Prompt for missing options
for var in instance hostname new_db_root new_db_pass; do
  if [[ -z ${!var} ]]; then
    printf "Enter ${var//_/\ } : "
    if [[ "$var" == "new_db_pass" ]]; then
      read -s input
    else
      read input
    fi
    declare $var="$input"
  fi
done

# Enable and start Koha instances
for instancename in "${instance[@]}"; do
  koha_conf=/etc/koha/sites/$instancename/koha-conf.xml
  sudo rsync -a $koha_conf $koha_conf.$(date +%d_%b_%Hh%M_%Z)
  kohadbpwd=$(sudo xmlstarlet sel -t -v 'yazgfs/config/pass' $koha_conf)
  sudo xmlstarlet edit -L --update 'yazgfs/config/hostname' --value "$hostname" $koha_conf

  mysql -h ${hostname} -u ${new_db_root} -p${new_db_pass} -e "
  CREATE DATABASE IF NOT EXISTS koha_${instancename};
  DROP USER IF EXISTS 'koha_${instancename}'@'%';
  CREATE USER IF NOT EXISTS 'koha_${instancename}'@'%' IDENTIFIED BY '${kohadbpwd}';
  GRANT ALL PRIVILEGES ON koha_${instancename}.* to 'koha_${instancename}'@'%';
  FLUSH PRIVILEGES;"
done

# Backup the koha-common.cnf and debian.cnf file
sudo rsync -a /etc/mysql/debian.cnf /etc/mysql/debian.cnf.$(date +%d_%b_%Hh%M_%Z)
sudo rsync -a /etc/mysql/koha-common.cnf /etc/mysql/koha-common.cnf.$(date +%d_%b_%Hh%M_%Z)

db_config="
[client]
host     = ${hostname}
user     = ${new_db_root}
password = ${new_db_pass}
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = ${hostname}
user     = ${new_db_root}
password = ${new_db_pass}
socket = /var/run/mysqld/mysqld.sock
"

# Update koha-common.cnf with config for remote db
echo "$db_config" | sudo tee /etc/mysql/koha-common.cnf >/dev/null

# Update debian.cnf with config for remote db
echo "$db_config" | sudo tee /etc/mysql/debian.cnf >/dev/null

# Reload koha-common and memcached
sudo systemctl restart koha-common.service memcached.service
echo "Success"
