#!/bin/bash

# This script installs koha-common and  dependencies on a bare-bones Ubuntu server.
# I've tested this on Ubuntu Server 20.04LTS but it should work on other Debian distros. 
# You will need to configure Apache config files (/etc/apache2/sites-enabled/)
# You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
# To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
# This script is interactive, so you'll be prompted for input at various stages.
# You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)

# Prompt the user for the name of your koha instance. Input something simple and easily distinguishable from other instances.
echo "You have the following Koha instances running on this server:"
echo $(koha-list)

printf "\n"

read -p "Enter the name of each  Koha instance you want to configure separated by a space: " -a kinstance

opac=""
staff=""

for instancename in "${kinstance[@]}"; do
	while
	read -p "Continue configuring $instancename.conf (y/n)" response && [[ $response =~ ^([yY][eE][sS]|[yY])$ ]] 
	do

		echo "Configuring $instancename.conf"

		printf ".......... \n"

			# Prompt user to enter their Staff URL
			read -p "Enter the your Staff url $instancename (Skip http:// or https://):" staffurl

			staff+=" ${staffurl}"

			# Replace ServerName with  OPAC url above
	                sudo sed  -i "/ServerName*/c\   ServerName $staffurl" /etc/apache2/sites-enabled/$instancename.conf

			# Prompt user to enter their OPAC domain/subdomain
			read -p "Enter the your OPAC url for $instancename (Skip http:// or https://):" opacurl

			opac+=" ${opacurl}"

			# Replace *ServerName with  OPAC url above
			sudo sed -i  "0,/ServerName $staffurl/s//ServerName $opacurl/" /etc/apache2/sites-enabled/$instancename.conf

			sudo less /etc/apache2/sites-enabled/$instancename.conf
	done

done
# Restart Apache
sudo systemctl restart apache2
