#!/bin/bash
# ------------------------------------------------------------------
# Author: Lennon Mazonde
# GitHub: @grandmaestr
# Title: koha-db-backup
# Description: 
#       This script backups and copies your database to an S3 bucket.
#       You must specify the path to the S3 bucket using an environment variable i.e.
#       in /etc/environment, add "S3_BUCKET=/path/to/s3/bucket".
#       You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
#       To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
#       You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)

# ------------------------------------------------------------------
#set -x 
#set -e

# Script version
VERSION=0.1.0
# Set the name of the script to variable
SCRIPT_NAME="$(basename ${0})"

# --- Dump and copy db to s3 --------------------------------------------
DUMP_DB(){
        # Set the path to koha_conf.xml
        koha_conf=/etc/koha/sites/$val/koha-conf.xml
        # Retrieve the Koha user, password, database hostname
        kohadbpwd=$(sudo xmlstarlet sel -t -v 'yazgfs/config/pass' $koha_conf)
        kohadbuser=koha_$val
        kohadbpath=$(sudo xmlstarlet sel -t -v 'yazgfs/config/hostname' $koha_conf)

        # Dump Koha database and copy to S3 bucket
        mysqldump -h${kohadbpath} -u${kohadbuser} -p${kohadbpwd} --single-transaction --databases  --no-tablespaces koha_$val  > /tmp/koha_$val-$(date +"%m-%d-%Y-%Hh%M").sql

        aws s3 cp  /tmp/koha_$val-$(date +"%m-%d-%Y-%Hh%M").sql $S3_BUCKET/database/$val/koha_$val-$(date +"%m-%d-%Y-%Hh%M").sql

        # delete temp file
        rm /tmp/koha_$val-$(date +"%m-%d-%Y-%Hh%M").sql
}
# --- Locks -------------------------------------------------------
LOCK_FILE=/tmp/$SCRIPT_NAME.lock
if [ -f "$LOCK_FILE" ]; then
        echo "Script is already running"
        exit
fi

trap "rm -f $LOCK_FILE" EXIT
touch $LOCK_FILE

# --- Body --------------------------------------------------------
# Enable and start  Koha instances
for val in $(koha-list); do

    # Dump and migrate Koha instance database from source to destination db server
    DUMP_DB

done