#!/bin/bash

# This script automatically configures the Apache config in /etc/apache2/sites-enabled/$instancename.conf after your Koha instance has been installed
# Using sed to configure your ServerName for name-based installation.

# List installed koha instances
echo "You have the following instances installed on your server: $(koha-list)"

# Prompt the user for the name of your koha instance
echo "Enter the name of the Koha instance you wish to configure:"

# Read the input and store in a variable
read instancename

# Prompt user to enter their OPAC domain/subdomain
echo
echo "Enter the your OPAC url only (Skip http:// or https://):"
read  opacurl
echo "Your OPAC url is: $opacurl"

# Replace ServerName with  OPAC url above
sudo sed -i "/ServerName $instancename.myDNSname.org/c\   ServerName $opacurl" /etc/apache2/sites-enabled/$instancename.conf

# Prompt user to enter their Staff URL
echo
echo "Enter the your Staff url only (Skip http:// or https://):"
read  staffurl
echo "Your Staff url is: $opacurl"

# Replace ServerName with  OPAC url above
sudo sed -i "/ServerName $instancename-intra.myDNSname.org/c\   ServerName $staffurl" /etc/apache2/sites-enabled/$instancename.conf
