#!/bin/bash
# This script drops all your koha databases. Be very careful!

# Prompt the user for the name of your koha instance(s). Input something simple and easily distinguishable from other instances.
read -p "Enter the name of each  Koha instance you want activate separated by a space:	" -a instance

# Prompt the user for the remote database endpoint
read -p "Enter the URL/endpoint of your database server:   " hostname

# Prompt user for root user of remote database server
read -p "Enter the username of your remote database root user:	" remotedbroot

# Prompt user for password of remote database server
read -p  "Enter the password for the root user of your remote database server:	" remotedbpwd

# Prompt user for IP address of client server. If using AWS EC2 instances, enter the private IP
read -p "Enter the IP address of your client server (i.e. the server runnning the Koha web application):   " clientipaddr

# Enable and start  Koha instances
for instancename in "${instance[@]}"; do

# Delete mysql user

# Create Koha user in remote db server
mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} -e "
DROP DATABASE koha_${instancename};
delete from mysql.user where user like "koha%"
#DROP USER 'koha_${instancename}'@'${clientipaddr}';
FLUSH PRIVILEGES;"

done

# Display remaining databases and users
mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} -e "
SHOW DATABASES;
SELECT user, host from mysql.user;"

