#!/bin/bash

# This script restores the original config if run immediately after koha-config-encryption (immediately since each execution overwrrites /tmp/$i.koha-conf.xml

set -x

for i in $(koha-list); do
        # set path to koha-conf.xml
        configpath=/etc/koha/sites/$i/koha-conf.xml

	# restore original config
        cp /tmp/$i.koha-conf.xml $configpath
done
