#!/bin/bash

# This script installs koha-common and  dependencies on a bare-bones Ubuntu server.
# I've tested this on Ubuntu Server 20.04LTS but it should work on other Debian distros. 
# You will need to configure Apache config files (/etc/apache2/sites-enabled/)
# You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
# To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
# This script is interactive, so you'll be prompted for input at various stages.
# You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)


# Prompt the user for the name of your koha instance. Input something simple and easily distinguishable from other instances.
echo "Enter the name of your Koha instance:"

# Read the input and store in a variable
read instancename

# Prompt user to enter their OPAC domain/subdomain
echo "Enter the your OPAC url only (Skip http:// or https://):"
read  opacurl

# Prompt user to enter their Staff URL
echo "Enter the your Staff url only (Skip http:// or https://):"
read  staffurl


# Replace ServerName with  OPAC url above
sudo sed -i "/ServerName $instancename.myDNSname.org/c\   ServerName $opacurl" /etc/apache2/sites-enabled/$instancename.conf

# Replace ServerName with  OPAC url above
sudo sed -i "/ServerName $instancename-intra.myDNSname.org/c\   ServerName $staffurl" /etc/apache2/sites-enabled/$instancename.conf

# Restart Apache
sudo systemctl restart apache2

